services:
  psql:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  transaction-tracker:
    build: ./transaction-tracker
    ports:
      - "8080:8080"
    depends_on:
      psql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://psql:5432/postgres
      DB_USER: postgres
      DB_PASS: postgres
      API_KEY: ${API_KEY}
      API_SYMBOLS: ${API_SYMBOLS}