exchange_api:
  url: "https://api.twelvedata.com/eod"
  key: ${API_KEY}
  symbols: ${API_SYMBOLS}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
